"""热补丁导出字段定义（与 frontend/modules/constants/hotpatch-export-fields.js 对齐）。"""
from __future__ import annotations

from typing import Any

HOTPATCH_EXPORT_SYSTEM_FIELDS: list[dict[str, Any]] = [
    {"key": 'processId', "label": '流程ID', "type": 'system'},
    {"key": 'currentStage', "label": '当前阶段', "type": 'system'},
    {"key": 'currentHandler', "label": '当前处理人', "type": 'system'},
    {"key": 'slaTime', "label": 'SLA时间', "type": 'system'},
    {"key": 'creatorName', "label": '创建者', "type": 'system'},
]

HOTPATCH_EXPORT_FIELDS_BY_NODE: dict[str, list[dict[str, Any]]] = {
    "system": HOTPATCH_EXPORT_SYSTEM_FIELDS,
    "hp_demand_fill": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": 'fill_date', "label": '填写日期', "type": 'date'},
        {"key": 'dts_no', "label": 'DTS单号', "type": 'text'},
        {"key": 'dts_desc', "label": 'DTS描述', "type": 'text'},
        {"key": 'dts_baseline_version', "label": 'DTS基线版本', "type": 'text'},
        {"key": 'problem_type', "label": '问题类型', "type": 'whitelist'},
        {"key": 'expected_patch_version', "label": '期望补丁版本', "type": 'whitelist'},
        {"key": '期望补丁时间', "label": '期望补丁时间', "type": 'date'},
        {"key": '是否有规避手段', "label": '是否有规避手段', "type": 'whitelist'},
        {"key": '是否接受冷不丁', "label": '是否接受冷不丁', "type": 'whitelist'},
        {"key": '局点', "label": '局点', "type": 'text'},
        {"key": '问题登记人', "label": '问题登记人', "type": 'text'},
        {"key": '运维人员', "label": '运维人员', "type": 'text'},
        {"key": '开发责任人', "label": '开发责任人', "type": 'text'},
        {"key": '客户特殊诉求', "label": '客户特殊诉求', "type": 'richtext', "stripImages": True},
        {"key": '热补丁必要性说明', "label": '热补丁必要性说明', "type": 'richtext', "stripImages": True},
        {"key": '问题现象及触发场景', "label": '问题现象及触发场景', "type": 'richtext', "stripImages": True},
        {"key": '备注', "label": '备注', "type": 'richtext', "stripImages": True},
        {"key": '局点信息附件', "label": '局点信息附件', "type": 'file'},
    ],
    "hp_dev_fill": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": 'hp_de', "label": 'DE', "type": 'whitelist'},
        {"key": 'hp_se', "label": 'SE', "type": 'whitelist'},
        {"key": 'hp_pl', "label": 'PL', "type": 'whitelist'},
        {"key": 'hp_xm', "label": 'XM', "type": 'whitelist'},
        {"key": '责任田_xm组_', "label": '责任田（XM组）', "type": 'text'},
        {"key": '是否支持热补丁', "label": '是否支持热补丁', "type": 'whitelist'},
        {"key": '是否出过热补丁', "label": '是否出过热补丁', "type": 'whitelist'},
        {"key": '已修复热补丁版本号', "label": '已修复热补丁版本号', "type": 'text'},
        {"key": '是否必现', "label": '是否必现', "type": 'whitelist'},
        {"key": '总代码量_k_', "label": '总代码量（k）', "type": 'text'},
        {"key": '实际修改代码量_k_', "label": '实际修改代码量（k）', "type": 'text'},
        {"key": '问题现象', "label": '问题现象', "type": 'richtext', "stripImages": True},
        {"key": '触发因素', "label": '触发因素', "type": 'richtext', "stripImages": True},
        {"key": '触发概率', "label": '触发概率', "type": 'richtext', "stripImages": True},
        {"key": '问题根因', "label": '问题根因', "type": 'richtext', "stripImages": True},
        {"key": '问题影响', "label": '问题影响', "type": 'richtext', "stripImages": True},
        {"key": '规避措施', "label": '规避措施', "type": 'richtext', "stripImages": True},
    ],
    "hp_ccb": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '热补丁是否修复', "label": '热补丁是否修复', "type": 'whitelist'},
        {"key": '评审修复补丁版本', "label": '评审修复补丁版本', "type": 'text'},
        {"key": '结果确认', "label": '结果确认', "type": 'whitelist'},
        {"key": 'ccb与会人', "label": 'CCB与会人', "type": 'whitelist'},
        {"key": '是否影响管控', "label": '是否影响管控', "type": 'whitelist'},
        {"key": 'ccb时间', "label": 'CCB时间', "type": 'date'},
        {"key": '热补丁版本号', "label": '热补丁版本号', "type": 'text'},
        {"key": '评审遗留问题', "label": '评审遗留问题', "type": 'richtext', "stripImages": True},
        {"key": '热补丁发布目的', "label": '热补丁发布目的', "type": 'richtext', "stripImages": True},
        {"key": '目标客户', "label": '目标客户', "type": 'richtext', "stripImages": True},
        {"key": '管控验证点', "label": '管控验证点', "type": 'text'},
        {"key": '问题现象', "label": '问题现象', "type": 'text'},
    ],
    "hp_plan": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '测试人员', "label": '测试人员', "type": 'whitelist'},
        {"key": '开发人员', "label": '开发人员', "type": 'whitelist'},
        {"key": '热补丁单号', "label": '热补丁单号', "type": 'text'},
    ],
    "hp_assign_dev": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": 'hp_de', "label": 'DE', "type": 'whitelist'},
        {"key": 'hp_se', "label": 'SE', "type": 'whitelist'},
        {"key": 'hp_pl', "label": 'PL', "type": 'whitelist'},
        {"key": 'hp_xm', "label": 'XM', "type": 'whitelist'},
    ],
    "hp_assign_test": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": 'hp_tse', "label": 'TSE', "type": 'whitelist'},
        {"key": 'hp_te', "label": 'TE', "type": 'whitelist'},
    ],
    "hp_dev_analysis": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '热补丁dts单号', "label": '热补丁DTS单号', "type": 'text'},
        {"key": '此问题首次修复时间', "label": '此问题首次修复时间', "type": 'date'},
        {"key": '此问题首次修复对应版本号', "label": '此问题首次修复对应版本号', "type": 'text'},
        {"key": '补丁采用的是否为正式的修改方案', "label": '补丁采用的是否为正式的修改方案', "type": 'whitelist'},
        {"key": '责任田se是否评审通过', "label": '责任田SE是否评审通过', "type": 'whitelist'},
        {"key": '是否涉及内存野指针', "label": '是否涉及内存野指针', "type": 'whitelist'},
        {"key": '是否涉及跨责任田', "label": '是否涉及跨责任田', "type": 'whitelist'},
        {"key": '跨责任田确认人', "label": '跨责任田确认人', "type": 'whitelist'},
        {"key": '具体跨责任田', "label": '具体跨责任田', "type": 'text'},
        {"key": '是否需要长稳', "label": '是否需要长稳', "type": 'whitelist'},
        {"key": '修改涉及架构模块', "label": '修改涉及架构模块', "type": 'richtext', "stripImages": True},
        {"key": '修改涉及对外功能点', "label": '修改涉及对外功能点', "type": 'richtext', "stripImages": True},
        {"key": '打补丁前是否需要执行前置操作', "label": '打补丁前是否需要执行前置操作', "type": 'richtext', "stripImages": True},
        {"key": '打补丁后是否需要执行后置操作', "label": '打补丁后是否需要执行后置操作', "type": 'richtext', "stripImages": True},
        {"key": '修改方案', "label": '修改方案', "type": 'richtext', "stripImages": True},
        {"key": '举一反三', "label": '举一反三', "type": 'richtext', "stripImages": True},
        {"key": '方案影响分析', "label": '方案影响分析', "type": 'richtext', "stripImages": True},
        {"key": '开发自测情况', "label": '开发自测情况', "type": 'richtext', "stripImages": True},
        {"key": '高斯热补丁制作规范自检', "label": '高斯热补丁制作规范自检', "type": 'richtext', "stripImages": True},
        {"key": '涉及内存野指针的复现用例', "label": '涉及内存野指针的复现用例', "type": 'richtext', "stripImages": True},
        {"key": '修改影响', "label": '修改影响', "type": 'richtext', "stripImages": True},
        {"key": '开发测试建议', "label": '开发测试建议', "type": 'richtext', "stripImages": True},
        {"key": '定位过程', "label": '定位过程', "type": 'richtext', "stripImages": True},
    ],
    "hp_test_analysis": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": 'test_analysis_context', "label": '处理方式', "type": 'richtext', "stripImages": True},
        {"key": '前期漏测分析', "label": '前期漏测分析', "type": 'richtext', "stripImages": True},
        {"key": '测试方案', "label": '测试方案', "type": 'richtext', "stripImages": True},
        {"key": '现网和测试环境的差异', "label": '现网和测试环境的差异', "type": 'richtext', "stripImages": True},
        {"key": 'ci范围', "label": 'CI范围', "type": 'richtext', "stripImages": True},
    ],
    "hp_walkthrough": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '串讲是否通过', "label": '串讲是否通过', "type": 'whitelist'},
        {"key": 'hp_tse', "label": 'TSE', "type": 'whitelist'},
        {"key": 'hp_te', "label": 'TE', "type": 'whitelist'},
        {"key": 'hp_pm', "label": 'PM', "type": 'whitelist'},
        {"key": '工程人员', "label": '工程人员', "type": 'whitelist'},
    ],
    "hp_pm_check": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '补丁安装指导书是否就绪', "label": '补丁安装指导书是否就绪', "type": 'whitelist'},
        {"key": '补丁说明书是否就绪', "label": '补丁说明书是否就绪', "type": 'whitelist'},
        {"key": '截止完成时间', "label": '截止完成时间', "type": 'date'},
    ],
    "hp_de_check": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '代码是否已合入', "label": '代码是否已合入', "type": 'whitelist'},
        {"key": 'cmc版本自检结果', "label": 'Cmc版本自检结果', "type": 'whitelist'},
        {"key": '问题单是否走至cmo', "label": '问题单是否走至cmo', "type": 'whitelist'},
        {"key": '截止完成时间', "label": '截止完成时间', "type": 'date'},
    ],
    "hp_tse_check": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": 'ci范围是否圈定', "label": 'CI范围是否圈定', "type": 'whitelist'},
        {"key": '截止完成时间', "label": '截止完成时间', "type": 'date'},
    ],
    "hp_eng_check": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": 'cmc版本构建是否成功', "label": 'CMC版本构建是否成功', "type": 'whitelist'},
        {"key": '截止完成时间', "label": '截止完成时间', "type": 'date'},
    ],
    "hp_transfer_start": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '转测说明', "label": '转测说明', "type": 'richtext', "stripImages": True},
    ],
    "hp_transfer_confirm": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '确认转测', "label": '确认转测', "type": 'whitelist'},
        {"key": '转测打回原因', "label": '转测打回原因', "type": 'richtext', "stripImages": True},
        {"key": '转测打回次数', "label": '转测打回次数', "type": 'text'},
        {"key": '说明', "label": '说明', "type": 'text'},
    ],
    "hp_test_verify": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '测试结论', "label": '测试结论', "type": 'whitelist'},
        {"key": '满足热补丁规范', "label": '满足热补丁规范', "type": 'whitelist'},
        {"key": '补丁安装指导书是否撰写', "label": '补丁安装指导书是否撰写', "type": 'whitelist'},
        {"key": '补丁安装指导书测试是否通过', "label": '补丁安装指导书测试是否通过', "type": 'whitelist'},
        {"key": '补丁说明书哦测试是否通过', "label": '补丁说明书哦测试是否通过', "type": 'whitelist'},
        {"key": '复现情况', "label": '复现情况', "type": 'richtext', "stripImages": True},
        {"key": '单点问题回归情况', "label": '单点问题回归情况', "type": 'richtext', "stripImages": True},
        {"key": '发散测试情况', "label": '发散测试情况', "type": 'richtext', "stripImages": True},
        {"key": 'ci用例是否新增看护代码修改', "label": 'CI用例是否新增看护代码修改', "type": 'richtext', "stripImages": True},
        {"key": '代码测试覆盖分析', "label": '代码测试覆盖分析', "type": 'richtext', "stripImages": True},
        {"key": '性能测试情况', "label": '性能测试情况', "type": 'richtext', "stripImages": True},
        {"key": '兼容性测试情况', "label": '兼容性测试情况', "type": 'richtext', "stripImages": True},
        {"key": '遗留风险', "label": '遗留风险', "type": 'richtext', "stripImages": True},
    ],
    "hp_bu_conclusion": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '混合云验证结果', "label": '混合云验证结果', "type": 'whitelist'},
        {"key": '公有云验证结果', "label": '公有云验证结果', "type": 'whitelist'},
    ],
    "hp_review_publish": [
        {"key": 'stage_handler', "label": '处理人', "type": 'text'},
        {"key": '是否组织发布评审', "label": '是否组织发布评审', "type": 'whitelist'},
        {"key": '资料评审是否通过', "label": '资料评审是否通过', "type": 'whitelist'},
        {"key": 't2t是都完成', "label": 'T2T是都完成', "type": 'whitelist'},
        {"key": 'orm电子流是否已签发', "label": 'ORM电子流是否已签发', "type": 'whitelist'},
    ],
}

HOTPATCH_NODE_LABELS: dict[str, str] = {
    'system': '系统字段',
    'hp_demand_fill': '诉求填写',
    'hp_dev_fill': '开发填写',
    'hp_ccb': '热补丁CCB',
    'hp_plan': '计划制定',
    'hp_assign_dev': '指定开发',
    'hp_assign_test': '指定测试',
    'hp_dev_analysis': '开发分析',
    'hp_test_analysis': '测试分析',
    'hp_walkthrough': '热补丁串讲',
    'hp_pm_check': 'PM自检',
    'hp_de_check': 'DE自检',
    'hp_tse_check': 'TSE自检',
    'hp_eng_check': '工程人员自检',
    'hp_transfer_start': '转测发起',
    'hp_transfer_confirm': '转测确认',
    'hp_test_verify': '测试验证',
    'hp_bu_conclusion': 'BU测试结论',
    'hp_review_publish': '评审发布',
}

HOTPATCH_NODE_ORDER: list[str] = [
    'system',
    'hp_demand_fill',
    'hp_dev_fill',
    'hp_ccb',
    'hp_plan',
    'hp_assign_dev',
    'hp_assign_test',
    'hp_dev_analysis',
    'hp_test_analysis',
    'hp_walkthrough',
    'hp_pm_check',
    'hp_de_check',
    'hp_tse_check',
    'hp_eng_check',
    'hp_transfer_start',
    'hp_transfer_confirm',
    'hp_test_verify',
    'hp_bu_conclusion',
    'hp_review_publish',
]

